version: "3"

services:
  redis:
    image: redis:alpine3.9
    container_name: "rates_redis"
    volumes:
      - redis_data:/data
  mysql:
    image: mysql:latest
    container_name: "rates_mysql"
    command:
      - "--max_allowed_packet=32505856"
    ports:
      - "3306:3306"
    env_file:
      - ./docker/mysql/.env
    volumes:
      - db_data_new:/var/lib/mysql
  front:
    image: abiosoft/caddy
    container_name: "rates_front"
    ports:
      - 80:80
    volumes:
      - ./docker/caddy/Caddyfile:/etc/Caddyfile
      - .:/app
    depends_on:
      - app
  app:
    image: rates_app:alpine
    build: ./docker/
    container_name: "rates_app"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
volumes:
  db_data_new:
  redis_data:
